# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
